<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Integrations ADD NEW IMPORT</name>
   <tag></tag>
   <elementGuidId>a7abf82c-71ec-4703-9767-8218016d2dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/integrations/div/header/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.section-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c0402ac-3f92-49bc-bfff-ea6d501f5f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>4482e165-0d2e-4b34-a389-0d3f93e7d253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Integrations ADD NEW IMPORT </value>
      <webElementGuid>b8d11b62-ba5f-4b63-822e-df5a4e6d6a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/integrations[1]/div[@class=&quot;connections&quot;]/header[1]/div[@class=&quot;section-header&quot;]</value>
      <webElementGuid>7d308322-7ef2-4e97-9650-8f6f9c870c77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/integrations/div/header/div</value>
      <webElementGuid>20e1b13f-d2ab-445b-bba8-3e581fe9f291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/following::div[3]</value>
      <webElementGuid>ce29c4ab-c6d2-40a4-9ec9-582ec048279c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period Configuration'])[1]/following::div[3]</value>
      <webElementGuid>13b85da9-061f-409e-9150-b5f82c91a817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>8d7bec89-eb16-43d4-a7a5-41ce9f087fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Integrations ADD NEW IMPORT ' or . = ' Integrations ADD NEW IMPORT ')]</value>
      <webElementGuid>1ae6a4ea-35d7-4ac8-9806-dc6639039498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
