<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name</name>
   <tag></tag>
   <elementGuidId>5ce4c469-81ba-4ad2-8a48-58a94812aa7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/integrations/div/section/wj-flex-grid/div/div[5]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wj-cell.wj-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ddde46b-a2fe-4669-acf3-e0722ba677d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wj-cell wj-header</value>
      <webElementGuid>9323c204-424d-4710-88cd-e168269573ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>994e233d-5567-497a-9219-c443f27afa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4a6a53d-0663-41a4-b8df-a7c624662e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>272ba0e0-ae8d-4a51-8b1b-1217b921e8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/integrations[1]/div[@class=&quot;connections&quot;]/section[@class=&quot;connections-content&quot;]/wj-flex-grid[@class=&quot;wj-control wj-content wj-flexgrid wj-state-readonly wj-state-focus wj-state-focused&quot;]/div[1]/div[5]/div[@class=&quot;wj-colheaders&quot;]/div[@class=&quot;wj-row&quot;]/div[@class=&quot;wj-cell wj-header&quot;]</value>
      <webElementGuid>68f9e83c-3b79-4f52-9e18-000fdb79a167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/integrations/div/section/wj-flex-grid/div/div[5]/div/div/div</value>
      <webElementGuid>52a6c1ff-a42e-4ca5-91e5-d7b3332fa356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mindy Kim'])[4]/following::div[12]</value>
      <webElementGuid>bbcd563e-d8a2-4ed6-9392-3cfc20e1dfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamics 365 Operations'])[2]/following::div[17]</value>
      <webElementGuid>1494a275-e915-4387-a6d4-faaff102c2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[2]/preceding::div[1]</value>
      <webElementGuid>6f0e6258-012d-4dba-bdf2-245ad7d0cd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::div[2]</value>
      <webElementGuid>497ca6c7-1b8f-442a-b7c4-cffa0cf6059c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>c543c414-417e-4cf1-8e41-e01ace9d7b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>89ddee96-479f-471c-a212-fba451fc9c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
