<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dw_loader</name>
   <tag></tag>
   <elementGuidId>ca53541f-1d38-44ea-99fc-8d675a960603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ball-clip-rotate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
