<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>77a5a8ee-3bbc-475d-a072-0233c3d937ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e23e35f-4822-4cb2-a039-45363e65ae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osr-text-box__input  ng-empty</value>
      <webElementGuid>30ae687c-c14c-4502-b83f-e05bac9ff024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cebf3331-4ca9-4530-80c1-045c37c1542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.ngModel</value>
      <webElementGuid>94944821-18fb-41a5-958a-23a32c1705f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>email-text-box</value>
      <webElementGuid>d215a288-02f4-4ef9-b142-85ff848c5662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__single_spa_angular_1&quot;)/ui-view[@class=&quot;ultimate ng-scope&quot;]/div[@id=&quot;fullscreen-root-container&quot;]/div[@class=&quot;login osrFlexItem&quot;]/div[@class=&quot;osrFlex&quot;]/div[@class=&quot;widget widget_container-login-form osrFlexItem osrFlexItem__grow ng-scope&quot;]/osr-login[@class=&quot;ng-scope ng-isolate-scope&quot;]/osr-email-input[@class=&quot;ng-scope ng-isolate-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/osr-label[@class=&quot;ng-isolate-scope&quot;]/ng-transclude[1]/osr-text-box[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope ng-empty&quot;]/div[@class=&quot;osr-text-box&quot;]/input[@class=&quot;osr-text-box__input  ng-empty&quot;]</value>
      <webElementGuid>8b9cd225-a3f2-4381-811f-a0588d7f6ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>d819c069-3d54-41f2-adb1-2346698c3720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fullscreen-root-container']/div/div/div[2]/osr-login/osr-email-input/form/osr-label/ng-transclude/osr-text-box/div/input</value>
      <webElementGuid>84d92ae8-f0c7-4460-8714-ae7fbc23b10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>21ba5ffd-0212-4cfc-9d36-45671112b373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email']</value>
      <webElementGuid>893e8077-7447-4b19-b54b-e019d98e11be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
