<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_model.Password</name>
   <tag></tag>
   <elementGuidId>20ffa109-fadc-4a2c-ba95-c9c494fa2222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='model.Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;model.Password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35ba3f03-9bdc-4e6d-b019-7ce91eab3433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed95da87-2dc4-47d0-95e8-6e911fc1746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-type</name>
      <type>Main</type>
      <value>{{ vm.showPassword ? 'text' : 'password' }}</value>
      <webElementGuid>fd4932de-8e4f-48e6-a8c7-69442e34f760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>model.Password</value>
      <webElementGuid>52a61a8a-8344-4e18-a5e8-b7c5f6e091e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osr-text-box__input ng-untouched ng-valid ng-valid-required ng-valid-minlength ng-valid-policy ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>e10c9c82-283b-4551-8cd3-d4a4be40e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.ngModel</value>
      <webElementGuid>7cc5db29-664e-4de1-9c30-febec7c38a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.onChange()</value>
      <webElementGuid>1e3c883a-2599-4d33-8637-e54107279a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>vm.required</value>
      <webElementGuid>395af423-9940-4e56-b5c2-8e75a53965cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vm.ngDisabled</value>
      <webElementGuid>138560e6-e3ec-4e85-91e6-e4cefbaa1232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4ca0033d-9dfa-46b3-9451-79acf62f7535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55620f05-a235-4d9e-9ec1-d654757a2dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-autocomplete</name>
      <type>Main</type>
      <value>{{vm.autocomplete == false ? 'off' : ''}}</value>
      <webElementGuid>45ad2f63-3eb2-410c-94d0-482ca63968c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__single_spa_angular_1&quot;)/ui-view[@class=&quot;ultimate ng-scope&quot;]/div[@id=&quot;fullscreen-root-container&quot;]/div[@class=&quot;login osrFlexItem&quot;]/div[@class=&quot;osrFlex&quot;]/div[@class=&quot;widget widget_container-login-form osrFlexItem osrFlexItem__grow ng-scope&quot;]/osr-login[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/osr-login-osr[@class=&quot;ng-scope ng-isolate-scope&quot;]/form[@class=&quot;ng-valid ng-scope ng-valid-email ng-valid-required ng-valid-minlength ng-valid-policy ng-dirty ng-valid-parse&quot;]/osr-label[@class=&quot;ng-isolate-scope&quot;]/ng-transclude[1]/osr-password-box[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope ng-not-empty&quot;]/div[@class=&quot;ng-valid ng-valid-required ng-valid-minlength ng-valid-policy ng-dirty ng-valid-parse&quot;]/div[@class=&quot;osr-text-box&quot;]/input[@class=&quot;osr-text-box__input ng-untouched ng-valid ng-valid-required ng-valid-minlength ng-valid-policy ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>9fbab300-430b-4d97-b38f-fd27555d610d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='model.Password']</value>
      <webElementGuid>cf894bbc-bb90-47bb-a784-d9ef6d2a1da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fullscreen-root-container']/div/div/div[2]/osr-login/div/osr-login-osr/form/osr-label/ng-transclude/osr-password-box/div/div/input</value>
      <webElementGuid>48c1bb6a-dd51-4c08-9496-c5194bca9ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d29fe885-3cf4-4785-84d4-d3ba4993fc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'model.Password']</value>
      <webElementGuid>27450cd3-4fed-4ac1-a53f-906edcf076f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
