<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menutoggledw</name>
   <tag></tag>
   <elementGuidId>8528cde6-9b01-4990-8533-972e0d8957d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a#menu-toggle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
