<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2016  2017  2018  2019  2020  2021  202_65064a</name>
   <tag></tag>
   <elementGuidId>579fc935-1d65-4c72-9d5f-1372600c28c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/period-configuration/div/section/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.preview-years.d-flex.flex-row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba7fb3c8-0469-45f9-8d29-7d2ce678663d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>preview-years d-flex flex-row</value>
      <webElementGuid>315d7282-2022-443c-a0e7-e698fcd162f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2016  2017  2018  2019  2020  2021  2022  2023  2024  2025  2026  2027 Edit 2023</value>
      <webElementGuid>0d42cdad-2443-40fa-b40c-3361fdd6b52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/period-configuration[1]/div[@class=&quot;adminperiodconfiguration&quot;]/section[@class=&quot;adminperiodconfiguration-content&quot;]/div[@class=&quot;adminperiodconfiguration-content-area&quot;]/div[@class=&quot;preview-period&quot;]/div[@class=&quot;preview-years d-flex flex-row&quot;]</value>
      <webElementGuid>9a23b119-02b7-4e8b-b8e3-b3f14d175212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/period-configuration/div/section/div/div/div</value>
      <webElementGuid>260354fb-4d5b-4100-b697-b2fb663a7f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period Configuration'])[3]/following::div[3]</value>
      <webElementGuid>6dedde91-4ed2-42b9-9405-b33c0a69c67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/following::div[6]</value>
      <webElementGuid>53e52c23-b614-4370-b559-d9b1ba9ff0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period'])[1]/preceding::div[7]</value>
      <webElementGuid>5f1d0936-b8d7-47a8-bbdd-72029257bffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>e1fcf60d-23f5-42ca-80ee-7cd26601f55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 2016  2017  2018  2019  2020  2021  2022  2023  2024  2025  2026  2027 Edit 2023' or . = ' 2016  2017  2018  2019  2020  2021  2022  2023  2024  2025  2026  2027 Edit 2023')]</value>
      <webElementGuid>fa36a5d6-c406-4965-9b69-8e986d109dfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
