<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Period</name>
   <tag></tag>
   <elementGuidId>0f80b717-0107-4aa6-93a5-884057308cd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/period-configuration/div/section/div/div/div[2]/table/thead/tr/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>d3fabe55-6ea6-4b7b-90ec-da67425e8f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Period</value>
      <webElementGuid>e7954bb1-5dcf-4727-8795-76019d2286ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/period-configuration[1]/div[@class=&quot;adminperiodconfiguration&quot;]/section[@class=&quot;adminperiodconfiguration-content&quot;]/div[@class=&quot;adminperiodconfiguration-content-area&quot;]/div[@class=&quot;preview-period&quot;]/div[@class=&quot;table-responsive&quot;]/table[1]/thead[1]/tr[1]/th[1]</value>
      <webElementGuid>749c7201-a347-41e8-8e29-9d786206adc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/period-configuration/div/section/div/div/div[2]/table/thead/tr/th</value>
      <webElementGuid>a6a5be39-99ab-4c78-924b-9628e168d475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit 2023'])[1]/following::th[1]</value>
      <webElementGuid>f8d86434-7cb0-4fa7-a04b-ecfb432dff2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period Configuration'])[3]/following::th[1]</value>
      <webElementGuid>0cca5e5e-f7d6-45ed-936b-64590eeec6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fiscal Period'])[1]/preceding::th[1]</value>
      <webElementGuid>87b7626e-aeeb-4128-9a83-39abf07ae102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fiscal Label'])[1]/preceding::th[2]</value>
      <webElementGuid>5495fa97-8346-4a9f-a822-fc9eaa599e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Period']/parent::*</value>
      <webElementGuid>21ee8efb-44e5-4f09-8214-3da61b691472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>983cb637-9e2f-41fc-931b-5e28f014d9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Period' or . = 'Period')]</value>
      <webElementGuid>d7cfd030-dc18-47c9-8226-be5aaa037831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
