<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Event Log</name>
   <tag></tag>
   <elementGuidId>e1393b0c-4481-43ec-870d-3a87b1c3be20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/event-log/section/header/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.section-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a053e3a4-7a24-4167-8eb5-e184ffc74768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>dcbd3cf9-00b1-45f5-b794-572a81fa15b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Event Log </value>
      <webElementGuid>a0448f67-4c6d-4f47-8be3-7a5c56c3793e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/event-log[1]/section[@class=&quot;section event-log&quot;]/header[1]/div[@class=&quot;section-header&quot;]</value>
      <webElementGuid>3b37599a-5a33-45f5-a5e4-a64856c4e026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/event-log/section/header/div</value>
      <webElementGuid>ac1ffb19-8191-46d8-9afb-27b286eeb904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/following::div[2]</value>
      <webElementGuid>c53051bf-62e3-40d1-908d-0a6b8cd2db34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period Configuration'])[1]/following::div[2]</value>
      <webElementGuid>26a82c59-09d8-45bc-962e-b76f81ab6b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[9]</value>
      <webElementGuid>a1183881-4e55-4bd7-8f61-561ec8c7c0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>34155d8b-36a8-4324-be1b-ee5d743830fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Event Log ' or . = ' Event Log ')]</value>
      <webElementGuid>1c50c7d8-2987-4cb4-8438-84ef58be48c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
