<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name</name>
   <tag></tag>
   <elementGuidId>6b3a4d6b-18d0-449c-9d29-8e783f858f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/event-log/section/section/wj-flex-grid/div/div[5]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wj-cell.wj-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2aecfac-6928-4d81-bba7-e93b0f41f3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wj-cell wj-header</value>
      <webElementGuid>e59e2498-a98c-4c9f-bfd7-3090519b3071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>42947c34-63bf-4a13-b5a2-a58d72a1303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a077db44-efd7-47c0-8961-faa6e4272a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>2c4a52a3-394d-4b0f-a80b-df5825d2192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/event-log[1]/section[@class=&quot;section event-log&quot;]/section[@class=&quot;section--content&quot;]/wj-flex-grid[@class=&quot;wj-control wj-content wj-flexgrid wj-state-readonly wj-state-focus wj-state-focused&quot;]/div[1]/div[5]/div[@class=&quot;wj-colheaders&quot;]/div[@class=&quot;wj-row&quot;]/div[@class=&quot;wj-cell wj-header&quot;]</value>
      <webElementGuid>2c5f22dd-eb3d-4ac6-ac2c-316aab8ab5cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/event-log/section/section/wj-flex-grid/div/div[5]/div/div/div</value>
      <webElementGuid>93bc033d-c85b-4cdc-b0d8-352e469713d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error Details'])[14]/following::div[11]</value>
      <webElementGuid>ee25b229-6b5a-4e5e-9745-5cbeab55cb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fail'])[14]/following::div[15]</value>
      <webElementGuid>005c27cd-c66d-4291-8784-710d7f42f18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[2]/preceding::div[1]</value>
      <webElementGuid>3b017d2b-cbc6-4210-a612-a96d72114eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::div[2]</value>
      <webElementGuid>eeea987c-52ad-48b1-a095-30bf99ec27c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>64ba66f4-87ca-4188-b2d5-dba5f43bb0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>ad9f493d-1fbb-4119-81fb-bfc51851aaeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
