<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Period</name>
   <tag></tag>
   <elementGuidId>b1d91648-3f1c-4109-89cd-59f432872cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/monthly-rates/div/section/wj-flex-grid/div/div[5]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wj-cell.wj-header.wj-filter-off</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59111ae8-1871-41d1-9c0d-c028a54fd7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wj-cell wj-header wj-filter-off</value>
      <webElementGuid>2809924a-6f2b-44d4-b65c-361696a59871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a7c7a238-8978-4897-83b4-031c802253c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>496a4eb3-fde1-48e9-bc1f-a86bcf893bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Period</value>
      <webElementGuid>cf274b60-8514-4b52-904a-5ddb88522897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/monthly-rates[1]/div[@class=&quot;monthlyRates&quot;]/section[@class=&quot;monthlyRates-content&quot;]/wj-flex-grid[@class=&quot;wj-control wj-content wj-flexgrid wj-state-focus wj-state-focused&quot;]/div[1]/div[5]/div[@class=&quot;wj-colheaders&quot;]/div[@class=&quot;wj-row&quot;]/div[@class=&quot;wj-cell wj-header wj-filter-off&quot;]</value>
      <webElementGuid>bc7089bf-3340-4d3e-8173-699522aa75b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/monthly-rates/div/section/wj-flex-grid/div/div[5]/div/div/div</value>
      <webElementGuid>7fb3eb04-fadc-492d-8db5-58faf065ff95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April 30, 2017'])[1]/following::div[15]</value>
      <webElementGuid>df0cf4ca-eda2-4693-a732-0cdda1f3c18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March 31, 2017'])[1]/following::div[22]</value>
      <webElementGuid>361099c7-8737-41b9-b25d-5d5d39938cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar End'])[2]/preceding::div[1]</value>
      <webElementGuid>df5b9bdd-ae64-4f84-90f8-220b92671d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAD'])[2]/preceding::div[2]</value>
      <webElementGuid>0f16bc3a-c58d-4089-8741-3af1e24b273b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>66e4223a-5057-45e9-9280-4ae86d906c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Period' or . = 'Period')]</value>
      <webElementGuid>f9f80bfb-c63d-4b38-af30-ea3778a1e27a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
