<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PeriodCalendar EndCADEURHKDUSD</name>
   <tag></tag>
   <elementGuidId>0c9ac5ff-cce3-4c16-852b-afa642f8ab70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/monthly-rates/div/section/wj-flex-grid/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>wj-flex-grid.wj-control.wj-content.wj-flexgrid.wj-state-focus.wj-state-focused > div > div:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f607d24a-09e4-4176-b219-469f3d3860dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wj-part</name>
      <type>Main</type>
      <value>ch</value>
      <webElementGuid>a7b9211e-c5e9-4873-aaa9-2e52142887fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c72af9a-d7b7-4587-ab94-8ac4a3ee6b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PeriodCalendar EndCADEURHKDUSD</value>
      <webElementGuid>73ef55aa-7373-4569-a43f-4dc33583bb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper&quot;]/monthly-rates[1]/div[@class=&quot;monthlyRates&quot;]/section[@class=&quot;monthlyRates-content&quot;]/wj-flex-grid[@class=&quot;wj-control wj-content wj-flexgrid wj-state-focus wj-state-focused&quot;]/div[1]/div[5]</value>
      <webElementGuid>cb87d7ce-fab7-4291-9a18-a24129b70930</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/monthly-rates/div/section/wj-flex-grid/div/div[5]</value>
      <webElementGuid>7407b12e-c7af-462b-8a3b-5eaa84523a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April 30, 2017'])[1]/following::div[12]</value>
      <webElementGuid>cd9ddf42-a0a5-4e97-af94-e4b87931cd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March 31, 2017'])[1]/following::div[19]</value>
      <webElementGuid>e6485439-d661-4a9e-9f4e-855421e6d08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//wj-flex-grid/div/div[5]</value>
      <webElementGuid>61219b74-167e-42ba-8350-5ea09c3341ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PeriodCalendar EndCADEURHKDUSD' or . = 'PeriodCalendar EndCADEURHKDUSD')]</value>
      <webElementGuid>59b30202-c6e1-4a56-abcf-197fa5ba58dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
