<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectRateType</name>
   <tag></tag>
   <elementGuidId>ded04c64-10af-43d9-9d08-13dd96c88c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.placeholder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
