<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enabling World Class Decision Making_foreground-banner container</name>
   <tag></tag>
   <elementGuidId>66d99858-b7c1-4e6d-ba84-394feea9cfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.foreground-banner.container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09f27aa3-8316-412d-b3bb-1e04c925ca6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foreground-banner container</value>
      <webElementGuid>23be42e2-518e-4ae7-82ce-14801a4f6264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/a[1]/div[@class=&quot;banner-container mb-6&quot;]/div[@class=&quot;foreground-banner-container&quot;]/div[@class=&quot;foreground-banner container&quot;]</value>
      <webElementGuid>33a5de80-4ae6-4992-bac2-eb18861abcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Home - Solver/iframe_Welcome, Mindy Kim_iFrameResizer0</value>
      <webElementGuid>52717749-21e5-4987-a4e1-354e6c9e3fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>8ea903b9-4e69-4530-9d3a-b1f8de1ba35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
