<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Mindy Kim_iFrameResizer0</name>
   <tag></tag>
   <elementGuidId>6bdb6355-39a4-422e-803f-d71f7a5596ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iFrameResizer0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iFrameResizer0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>71293b30-ea67-4fe0-87e5-d280b115b0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LandingPage</value>
      <webElementGuid>f335d6db-cd6d-4743-a266-79d092b19f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>javascript:iFrameResize({ log: false }, this)</value>
      <webElementGuid>217250eb-592e-4ec2-a1ae-8564a1a6c92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>ef27b875-2727-4115-a411-eec90811e23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://solverdevportalhome.z19.web.core.windows.net/index.bf8c3364.html</value>
      <webElementGuid>322f6967-2b17-4b14-abb8-3877b4432020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iFrameResizer0</value>
      <webElementGuid>4340f287-72da-4262-95fc-923bb82b6b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>08a9ff1a-619c-4d3d-a743-1bc299493f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iFrameResizer0&quot;)</value>
      <webElementGuid>2fddea2e-68a8-42e6-be39-c2ad32c1d704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iFrameResizer0']</value>
      <webElementGuid>5962c7f0-49b7-407e-abb8-587122145c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:content@1.0.0']/div/div/div/div/div/iframe</value>
      <webElementGuid>77590156-f13f-4d7e-b1ed-e4f7499c0da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6687839b-1ea9-4b6d-80b6-01ff45b84ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'LandingPage' and @src = 'https://solverdevportalhome.z19.web.core.windows.net/index.bf8c3364.html' and @id = 'iFrameResizer0']</value>
      <webElementGuid>81103608-3130-4a3e-8db9-b616dd70aad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
