<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Mindy_Corporate_Demo_tenant-switcher-na_1fad51</name>
   <tag></tag>
   <elementGuidId>2776d361-9770-4826-abaf-35c2614cc2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Mindy_Corporate_Demo'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tenant-switcher-navigate-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e212c09e-ee81-4661-9fe5-b936212c8c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>navigate-down</value>
      <webElementGuid>53f3b92d-f256-4e4d-81f7-33aeaac03190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenant-switcher-navigate-down</value>
      <webElementGuid>0ad154e3-6f97-45fe-b849-92025342705e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon--supersmall icon--silver</value>
      <webElementGuid>272ab8bf-ed72-4c62-857d-4ee88c3ae4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>97f73f4a-afd7-48e4-a21c-937958d14f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xml:space</name>
      <type>Main</type>
      <value>preserve</value>
      <webElementGuid>83320ae8-b1c7-4187-9165-4348b7cde5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024px</value>
      <webElementGuid>d2df7f76-43b7-4504-a6b2-b7123b57dc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1024px</value>
      <webElementGuid>eecbd8a7-51b4-4980-9a27-70af448fd205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape-rendering</name>
      <type>Main</type>
      <value>geometricPrecision</value>
      <webElementGuid>3d98f23b-de3d-4f8a-a218-6926f2916523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-rendering</name>
      <type>Main</type>
      <value>geometricPrecision</value>
      <webElementGuid>e5badd75-fffc-401b-bd94-e131142d5349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>image-rendering</name>
      <type>Main</type>
      <value>optimizeQuality</value>
      <webElementGuid>89666314-da1d-4c49-aeaf-aabb9dd25b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>nonzero</value>
      <webElementGuid>b2a19e73-3d90-4020-8b39-2686f7258980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>c9243d34-58c7-480c-8f83-36a8f53765d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 10240 10240</value>
      <webElementGuid>1d639aa5-54ae-48d8-8efb-4161b7588cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>dec021a4-426d-48a5-8a56-b498fb928e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenant-switcher-navigate-down&quot;)</value>
      <webElementGuid>d65165c1-6cb3-41c5-8288-25e71d8493f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mindy_Corporate_Demo'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>ee5b7136-e3bb-4339-8746-5b3749eb5527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mindy Kim'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>f32cbf0d-6bfa-42c6-bc3c-160e40c58a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>af08a6d3-3587-4aef-850a-cbd249bb7316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>82aabb67-a18e-4188-926b-930a9851de87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'tenant-switcher-navigate-down']</value>
      <webElementGuid>4b9ccd19-04d5-4063-8eb1-cda971c9be5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
