<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Modules Dimensions</name>
   <tag></tag>
   <elementGuidId>71b02277-6ec5-4a6b-a77a-fb430f566b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='solver-data-warehouse-app']/div/overview/section/solver-header-tab-bar/section/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.header-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45c1828e-a779-4a19-be21-40309cf92cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-tab</value>
      <webElementGuid>748f639f-e3d0-4878-9591-43ca1d41d1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modules Dimensions </value>
      <webElementGuid>55f37e52-9c46-438f-9503-5edd3fc19d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solver-data-warehouse-app&quot;)/div[@class=&quot;page-content-wrapper page-content-wrapper--wide&quot;]/overview[1]/section[@class=&quot;section&quot;]/solver-header-tab-bar[1]/section[@class=&quot;header&quot;]/div[@class=&quot;header-tab&quot;]</value>
      <webElementGuid>bc552701-e088-43db-8b43-0b329f190536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='solver-data-warehouse-app']/div/overview/section/solver-header-tab-bar/section/div</value>
      <webElementGuid>9b29ce56-a5ab-4748-824b-03429c1e6061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modules by Dimension'])[1]/following::div[1]</value>
      <webElementGuid>b0de92eb-1c64-45ac-9763-89002b6dbc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[3]/following::div[1]</value>
      <webElementGuid>4e00bc3b-6a8c-41eb-b19d-f5ec328b53dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//solver-header-tab-bar/section/div</value>
      <webElementGuid>a76b3891-ef49-44d3-98aa-317d1a30f7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Modules Dimensions ' or . = 'Modules Dimensions ')]</value>
      <webElementGuid>5bd1cf00-16d6-4b8f-9b90-861fd03539cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
